language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: P5Y9WEuwydC+AhBJz5FQf9EXCVLmWTw3xlAQnitI2sAVtbRlWvycdJhWXpEgKk6o3Yp0+fPrPoyvkEi+hWmScrpunOnMKz5QtasIA7ahaXIkBb7rf8eMYQX36NRLOl2zv5c8eGdD/q3v53TJuBXiOSfyUHeJFHT2jILrTgk2VxWgSROcv4vs9rBw9YiQirN11ULL99T7llZC7y5opGaTDc2lAMBlRAR4wq1PpWmMvvSY+84RA4XxuMHsv43Xt//OYD0XKRvAdLO8yze2killY/PK8Ori7D1EdSk3IMe6Yw4R7zqRz/1YO3C22sC+RijjO+11h5OJc9Q5EhRpTtZ0oFvdf+1YzCuiajtQgNhOgfsjAFZQSVT7I5Ia+nQ499r2XttXfDbVdWOM08wGLBn93wcEWDxmvHwf0yIlBBZDo64OCY0EzfPU+70eT6vLtsYhbvtRgaC3gWJa2ckGdcP64vmOX3Dv8oso7J6LZwiFnx9hogR2J1Ahsc+H7ufP+ermJReyLgaJjUAS6rB6RaKVBWUdV8JKZI2vbM2BS2b9dQXF8BNP1qmzGm9J76XbbQmhDwGTKoM6xmWQYtxEYl1T0FQls1STEtraLrAgATwbT6KelwWJt+BVldIIRprjogOC7Hu7JwlaOeXb7z+V+F03j232ID/oqUwKo6PIUVISZ2M=
  app: agile-tor-45205
  on:
    repo: rrcheatham/BlogAPI
